name: news_app
description: A new Flutter project.

 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
 
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.3.7
  ff_navigation_bar: ^0.1.4
  bottom_navy_bar: ^5.5.0
  provider: ^4.0.4
  rxdart: ^0.23.1  
  bmnav: ^0.3.4  
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.1
  scroll_snap_list: ^0.6.0
  auto_size_text: ^2.1.0
  #intl: ^0.17.0
  animated_splash_screen: ^1.0.1+2
  shimmer: ^1.1.2
  flutter_onboarding_screen: ^0.0.2
  equatable: ^1.2.5
  dartz: 0.9.0 
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
 
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
